### ISSUE TITLE
getUpgrade and getResearch in ResearchFacility

### ISSUE THREAD

**Issue by Venorcis** [OpenBW/BWAPI4J#12]
It would be useful to not only be able to check íf the building is upgrading/researching but also what it is upgrading/researching

**Comment by Bytekeeper** [comment]
This is fixed, you can call ```Researcher.getUpgradeInProgress``` and ```Researcher.getResearchInProgress```.

**Comment by adakitesystems** [comment]
Thanks @Venorcis for the feature request and @Bytekeeper for implementing it.
