### ISSUE TITLE
BWEM can't find path between bases on (2)Benzene.scx

### ISSUE THREAD

**Issue by Bytekeeper** [OpenBW/BWAPI4J#14]
The BWEM port can not find a path between the 2 bases in the SSCAIT map "(2)Benzene.scx".

**Comment by Bytekeeper** [comment]
This part of the port is wrong: C++ multimap keys are sorted, whereas the ported map is just a HashMap with no ordering gurantees:
```
final MultiValuedMap<Integer, ChokePoint> ToVisit = new ArrayListValuedHashMap<>(); // a priority queue holding the GetChokePoints to visit ordered by their distance to start.
                                                                                            //Using ArrayListValuedHashMap to substitute std::multimap since it sorts keys but not values.
```

vs
```
	multimap<int, const ChokePoint *> ToVisit;	// a priority queue holding the GetChokePoints to visit ordered by their distance to start.
```

**Comment by Bytekeeper** [comment]
Also, the equals implementation of ChokePoint is not valid regarding the A*:
```
    for (int i = 0; i < Targets.size(); ++i) {
                if (current.equals(Targets.get(i))) {
                    Distances.set(i, currentDist);
                    --remainingTargets;
                }
            }
```
As equals returns "true" if 2 different ChokePoints connect the same Areas.

**Comment by adakitesystems** [comment]
Thanks for looking into this.

> This part of the port is wrong: C++ multimap keys are sorted, whereas the ported map is just a HashMap with no ordering gurantees: [...]

As seen in the recently added test file [MultiMapPortTest.java](https://github.com/OpenBW/BWAPI4J/blob/49cb60ee7e1c1cdee966f36684d43c678c275d94/BWAPI4J/src/test/java/bwem/MultiMapPortTest.java), `ArrayListValuedHashMap` mimics C++ `std::multimap` whereas your implementation of `PriorityQueue<>(Comparator.comparingInt(a -> a.first));` does not according to the above test. The `PriorityQueue` implementation fails the test: [TEST_PriorityQueue](https://github.com/OpenBW/BWAPI4J/blob/49cb60ee7e1c1cdee966f36684d43c678c275d94/BWAPI4J/src/test/java/bwem/MultiMapPortTest.java#L104-L131).

1) Please clarify whether you're aware that Java's `PriorityQueue` does not mimic C++'s `std::multimap` behavior and/or if my claim is incorrect and I made a mistake in my test such that my test is irrelevant to the logic of the algorithm in [Graph.java:688:ComputeDistances](https://github.com/Bytekeeper/BWAPI4J/blob/master/BWAPI4J/src/main/java/bwem/Graph.java#L688-L775).

2) I have tested your changes and confirm your changes allow BWEM to return a path between the two starting locations on Benzene. However, please confirm or comment on whether or not this issue (https://github.com/OpenBW/BWAPI4J/issues/14) is now resolved via your commits. I am still seeing a bug in the `getPath` method which returns an extra node which is also an issue with my original port. Perhaps we can consider #14 fixed and a new issue can be opened for sub-optimal paths returned via `getPath`?

**Comment by Bytekeeper** [comment]
1) ```ArrayListValuedHashMap```: "Implements a ListValuedMap, using a HashMap to provide data storage and ArrayLists as value collections" - as you can see keys are not sorted, which is required for A*
Whereas ```std::multimap```: "Internally, the elements in a multimap are always sorted by its key following a specific strict weak ordering criterion indicated by its internal comparison object (of type Compare)."

A ```PriorityQueue``` is definitely not the same. But: The first "element" is always the smallest in regards of the Comparator. So I changed the implementation to use a sorted queue of "(Distance,ChokePoint)" instead of "(Distance,List<ChokePoints>)" - which in my opinion simplified the loop and should not deteriorate the performance.

**Comment by Bytekeeper** [comment]
2. I'm sorry, I did not check any further as to getting a path :) 
I added a test: https://github.com/Bytekeeper/BWAPI4J/commit/18412cc574c7decc72ef7249e5886011f050d630 that shows the problem with ArrayListValuedHashMap.

**Comment by adakitesystems** [comment]
Confirmed. `ArrayListValuedHashMap` is the wrong choice to replace `std::multimap`. As pointed out by @Bytekeeper, one observable case of `ArrayListValuedHashMap` not sorting keys is when the count of the container reaches 2^16 objects.

I consider the issue of BWEM not finding a path between the bases on Benzene as resolved thanks to @Bytekeeper's commits.

The "extra node" node issue has been opened as https://github.com/OpenBW/BWAPI4J/issues/16.

**Comment by adakitesystems** [comment]
Merged.
