### ISSUE TITLE
Extra node in paths returned from method "CPPath Graph.GetPath"

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#16]
Sometimes, the returned `CPPath` container contains an extra node. This issue is not present in the original C++ BWEM.

As seen in this code snippet from [Graph.java:190](https://github.com/OpenBW/BWAPI4J/blob/master/BWAPI4J/src/main/java/bwem/Graph.java#L190-L279) ...
````
    // Returns a list of ChokePoints, which is intended to be the shortest walking path from cpA to cpB.
    public CPPath GetPath(ChokePoint cpA, ChokePoint cpB) {
        return m_PathsBetweenChokePoints.get(cpA.Index().intValue()).get(cpB.Index().intValue());
    }
````
... `Graph.GetPath` is merely a regurgitating method. This means the issue with a suboptimal path could be in data calculated during the initialization phase, during [lines 195 to 275](https://github.com/OpenBW/BWAPI4J/blob/master/BWAPI4J/src/main/java/bwem/Graph.java#L195-L275), or somewhere else. I have tried some debugging but was unsuccessful.

**Comment by Bytekeeper** [comment]
The Area "Distance" algorithm had the same problem an was returning strange distances for the ChokePoint pathing. This is how it looks on my branch now:
https://imgur.com/0l7cTMz

**Comment by adakitesystems** [comment]
Excellent work! Thanks! I have only tested a few different paths manually but your fix seems to resolve the issue and it's a much needed fix regardless. I'll see what I can do for setting up automated tests for comparing path results against the original C++ BWEM.
