### ISSUE TITLE
What version of Visual Studio is supposed to open BWAPI4JBridge?

### ISSUE THREAD

**Issue by dgant** [OpenBW/BWAPI4J#2]
Tried two:

### 2013:
Project appears to use a newer C++ compiler than shipped with 2013; opens but won't build.

"Error MSB8020 The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools."

### 2015
Crashes on open

A common file naming convention is MySolutionName.vs2013.sln as a hint as to the intended Visual Studio version.

**Comment by OpenBW** [comment]
It's Visual Studio 2017 (community edition - free)
