### ISSUE TITLE
No way to check if the game is paused

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#22]
It's probably fairly straight-forward to implement using JNI, but I wonder if there is a way to check this condition without JNI. One use case for `isPaused` is to be used with manually tracking the frame number by incrementing it in the `onFrame` callback because the frame number does not change when the game is paused. If this is achievable, we can remove the dependency of calling the two JNI calls: `getFPSCount` and `isPaused`.

Any ideas/suggestions for alternatives to implementing `isPaused` without JNI?

**Comment by dgant** [comment]
You get pretty close by, in your onFrame handler, checking whether the current frame count is the same as it was last frame. This leads to the first frame of paused-ness being treated normally, then future consecutive frames of paused-ness being treated as such.

**Comment by Bytekeeper** [comment]
Alternatively we could just add ```isPaused``` in the data array that is passed and use the ```update``` method in ```InteractionHandler```.

**Comment by adakitesystems** [comment]
> You get pretty close by, in your onFrame handler, checking whether the current frame count is the same as it was last frame. This leads to the first frame of paused-ness being treated normally, then future consecutive frames of paused-ness being treated as such.

How do you check whether the current frame is the same as the last frame? Do you not have to call `getFPSCount or a similar function?

> Alternatively we could just add isPaused in the data array that is passed and use the update method in InteractionHandler.

Good idea.

**Comment by dgant** [comment]
The frame count, not the FPS. We already have that: https://github.com/OpenBW/BWAPI4J/blob/master/BWAPI4J/src/main/java/org/openbw/bwapi4j/BW.java#L41 :smile:
