### ISSUE TITLE
UnitType stats dont get updated depending on Player upgrades and researches

### ISSUE THREAD

**Issue by Jabbo16** [OpenBW/BWAPI4J#25]
Original BWAPI PlayerInterface allows to get current UnitType stats like armor or damage depending on that player upgrades, researches and Race.

Current bwapi methods affected are:

- Player.topSpeed(UnitType) -> moved to UnitType.topSpeed() in bwapi4j
- Player.armor(UnitType) -> moved to UnitType.armor() in bwapi4j
- Player.damage(UnitType) -> moved to UnitType.damage() in bwapi4j
- Player.weaponMaxRange(WeaponType) -> moved to WeaponType.maxRange() in bwapi4j

BWAPI4J methods are not updated dynamically like their original bwapi counterparts, returning only default values with no upgrades.

It would be cool and a nice addition to have these methods also return updated values.

PS: Thanks for all your work on this new API.

**Comment by adakitesystems** [comment]
Thanks for the report.

It looks like all the data is already being cached in BWAPI4J but just needs getters. An example of the original is:
````
//--------------------------------------------- ARMOR ------------------------------------------------------
int PlayerInterface::armor(UnitType unit) const
{
  int armor = unit.armor();
  armor += getUpgradeLevel(unit.armorUpgrade());
  if ( unit == UnitTypes::Zerg_Ultralisk && getUpgradeLevel(UpgradeTypes::Chitinous_Plating) > 0 )
    armor += 2;
  else if ( unit == UnitTypes::Hero_Torrasque )
    armor += 2;
  return armor;
}
````

The `getUpgradeLevel` method is already in class `Player`. So, it appears just the methods may need to be added for the dynamic similar to how it is in C++ BWAPI.

**Comment by Bytekeeper** [comment]
@adakitesystems Wouldn't it be better to the `PlayerUnit` etc. methods return the correct value? Ie. `PlayerUnit.topSpeed()` - and if someone wants the "original" value, he can query it directly from `UnitType`.
This would keep the Player API cleaner.

**Comment by adakitesystems** [comment]
Pull request #26 has been opened to address @Bytekeeper's comment.
