### ISSUE TITLE
Missing maxHitPoints and maxShields in PlayerUnit

### ISSUE THREAD

**Issue by JasperGeurtz** [OpenBW/BWAPI4J#34]
<strike>
    target.getInitialHitPoints();
returns 0 for enemy units (this might be logical but feels weird)

Also
</strike>

    target.getHitPoints() + target.getShields();
are accessible but 

    target.maxHitPoints() + target.maxShields();

can only be accessed via UnitType which can't be extracted via a PlayerUnit, so these methods should probably also be part of PlayerUnit (or make getUnitType() available)?

**Comment by dgant** [comment]
Does getInitialHitPoints work differently in BWAPI?

**Comment by JasperGeurtz** [comment]
Have not tested it
https://bwapi.github.io/class_b_w_a_p_i_1_1_unit_interface.html#a7190e23748c4b7d694c5237a5b94293a
Mentions that the value should be 0  if this unit was not a neutral unit at the beginning of the game.


While
```Java
bw.getUnits(bw.getInteractionHandler().self()).forEach(u -> System.out.println(u + ": " + u.getInitialHitPoints()));
```
returns
```
2:Terran_SCV: 60
3:Terran_SCV: 60
4:Terran_Command_Center: 1500
6:Terran_SCV: 60
8:Terran_SCV: 60
```
Enemy units get an initialHitPoints of 0

**Comment by JasperGeurtz** [comment]
Hmmm, nevermind, it only seems that the starting units from get an initialHitPoints, maybe they count as neutral at the start?

Still the most important thing is that maxHitPoints and maxShields are not available from a PlayerUnit

**Comment by adakitesystems** [comment]
> Still the most important thing is that maxHitPoints and maxShields are not available from a PlayerUnit

I don't understand. `PlayerUnit.getHitPoints()` and `PlayerUnit.maxHitPoints()` are both public methods of `PlayerUnit` as seen in [PlayerUnit.java](https://github.com/OpenBW/BWAPI4J/blob/master/BWAPI4J/src/main/java/org/openbw/bwapi4j/unit/PlayerUnit.java#L188-L196) The following code works for me:
````
for (final PlayerUnit unit : bw.getUnits(bw.getInteractionHandler().self())) {
    System.out.println(unit.maxHitPoints());
    System.out.println(unit.getHitPoints());
}
````
Please clarify the issue.

**Comment by adakitesystems** [comment]
Thank you for reporting the missing method @JasperGeurtz. Please re-open if this did not resolve the issue.
