### ISSUE TITLE
getAirWeapon### and getGroundWeapon### in PlayerUnit

### ISSUE THREAD

**Issue by Venorcis** [OpenBW/BWAPI4J#35]
Those functions are protected right now, but should be public? This seems to apply to all functions that use the getUnitStatCalculator

**Comment by adakitesystems** [comment]
Marking the `UnitStatCalculator`-related getters as protected in `PlayerUnit` is intentional. The rationale for this is to **remove** the visibility of specific getters from individual units such as a `Corsair` not having a ground weapon and a `Siege Tank` not having an air weapon. Thus, currently `corsair.getGroundWeapon###()` and `siegeTank.getAirWeapon###()` are not possible but `corsair.getAirWeapon###()` and `siegeTank.getGroundWeapon###()` are possible.

I don't think we can cleanly provide a public getter in `PlayerUnit` for the `UnitStatCalculator` object and it is not in the spirit of BWAPI4J to provide such unit stats to be accessible via `PlayerUnit`. I do see many other public getters in `PlayerUnit` but I am not sure whether that is intentional.

I'll look into this.

**Comment by Venorcis** [comment]
Thanks for the quick reply. For my implementation, it would be a real hassle if such functions are not available on a more abstract level. I'd have to make huge lists of checking for specific kinds of units, for which I'd then rather even use introspection on the PlayerUnit class to make the function that is there anyway available. I do not see a big issue with such functions returning 0 for unit's that do not have relevant weapons.

**Comment by adakitesystems** [comment]
The public getters in `PlayerUnit` should've been marked as protected and then exposed via the appropriate subclasses. Which means they will probably be marked as protected in a future commit.

As for your request for BWAPI4J to be more abstract implementation friendly, @dgant has also pushed for such behavior. One of BWAPI4J's initial goals was to provide a type-safe API and possibly have the project [TSBW4J](https://github.com/openbw/tsbw4j) merged into BWAPI4J. This is another reason why the getters in `PlayerUnit` are/will be protected.

I should probably make a GitHub Project soon to outline the following, but we agree and have decided a few months ago that we would accommodate the two mindsets after upcoming BWAPI4J release; one mindset that prefers a type-safe restricted approach and the other being a more raw or abstract friendly approach such as requested by @dgant and yourself, @Venorcis.

In the mean time, we would not like to make the weapon unit stat getters public. A suggestion for a workaround right now is for the user to create utility methods using the [GroundAttacker](https://github.com/OpenBW/BWAPI4J/blob/master/BWAPI4J/src/main/java/org/openbw/bwapi4j/unit/GroundAttacker.java) and [AirAttacker](https://github.com/OpenBW/BWAPI4J/blob/master/BWAPI4J/src/main/java/org/openbw/bwapi4j/unit/AirAttacker.java) interfaces. Examples:
````
public static Weapon getGroundWeapon(PlayerUnit unit) {
  if (unit instanceof GroundAttacker) {
    return ((GroundAttacker) unit).getGroundWeapon();
  } else {
    return null;
  }
}

public static int getGroundWeaponMaxRange(PlayerUnit unit) {
  if (unit instanceof GroundAttacker) {
    return ((GroundAttacker) unit).getGroundWeaponMaxRange();
  } else {
    return 0;
  }
}
````
or maybe something like this:
````
public static GroundAttacker getGroundAttackerUnit(PlayerUnit unit) {
  if (unit instanceof GroundAttacker) {
    return (GroundAttacker) unit;
  } else {
    return null;
  }
}

public static Weapon getGroundWeapon(GroundAttacker unit) {
  return (unit != null) ? unit.getGroundWeapon() : null;
}

public static int getGroundWeaponMaxRange(GroundAttacker unit) {
  return (unit != null) ? unit.getGroundWeaponMaxRange() : 0;
}
````
I realize this may not be ideal. However, we wish to maintain type-safety until we split BWAPI4J into the two different approaches.

**Comment by Venorcis** [comment]
Thanks for the explanation, clear!
