### ISSUE TITLE
Error codes should be available immediately

### ISSUE THREAD

**Issue by Bytekeeper** [OpenBW/BWAPI4J#37]
Issuing a command will not update the error code immediately, since it's only updated once per frame.
Either we should throw `Exceptions` if an error occurs, or return the error code or update the interaction handler error code immediately.

**Comment by adakitesystems** [comment]
We may have to make `getLastError` a pure JNI command with no caching. `GameImpl::setLastError` gets called for almost every command; even those such as `setScreenPosition`.
