### ISSUE TITLE
Mutalisks can't morph into Devourers

### ISSUE THREAD

**Issue by dgant** [OpenBW/BWAPI4J#4]
https://github.com/OpenBW/BWAPI4J/blob/master/BWAPI4J/src/main/java/org/openbw/bwapi4j/unit/Mutalisk.java#L15

**Comment by adakitesystems** [comment]
With much thanks and some small changes to @Bytekeeper's fix, this issue can be considered closed. It will remain open until merged into the main branch.

**Comment by adakitesystems** [comment]
A fix has been merged into branch `master`.
