### ISSUE TITLE
Building.getBuildUnit should not report an error if the unit is not an SCV

### ISSUE THREAD

**Issue by Bytekeeper** [OpenBW/BWAPI4J#42]
For addons at least, it is the attached building and not a SCV.

**Comment by adakitesystems** [comment]
We can ask @IMP-42 to verify this, but I believe the user is supposed to use `Addon#getMainBuilding()` instead of `Building#getBuildUnit()` and thus, this not a bug but product of strict typesafety design.

**Comment by Bytekeeper** [comment]
`Buildunit` should represent the unit "building it" or "what is this unit building" according to BWAPI. So for addons I think it should return the main building
