### ISSUE TITLE
Medic healing

### ISSUE THREAD

**Issue by MasterFocus** [OpenBW/BWAPI4J#47]
As per discussed on Discord:
- The `healing` method is confusing and perhaps could be renamed to `healUnit`, as it would express the intent of the method more crearly
- Perhaps there should be a method called `healMove` as well, which is basically the equivalent of ordering a Medic to "_attack_" a certain **position**

**Comment by adakitesystems** [comment]
Thanks for bug report, @MasterFocus. I added and tested the missing methods. The `healing` method has been renamed to `heal`. I like the name `healUnit` better, but we have `attack` and not `attackUnit`.

**Comment by MasterFocus** [comment]
For documentation purposes:

We initially agreed to use `AttackMove`:
`return issueCommand(this.id, Attack_Move, -1, position.getX(), position.getY(), queued ? 1 : 0);`

According to @adakitesystems:
- The following also works: `return issueCommand(this.id, Use_Tech_Position, -1, position.getX(), position.getY(), Healing.getId());`
- In both cases , `getOrder()` returns `Order.HealMove` while the Medic is walking and `Order.MedicHeal` when the Medic is actually healing a unit.
