### ISSUE TITLE
Refactor "Building#getLastKnown..." methods

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#49]
Example: https://github.com/OpenBW/BWAPI4J/blob/4ee22b569281cf3315ac3e9659449c64d0833f51/BWAPI4J/src/main/java/org/openbw/bwapi4j/unit/Building.java#L81-L165

**Comment by adakitesystems** [comment]
I added [BuildingTest](https://github.com/OpenBW/BWAPI4J/blob/774092fe3a9e0de1355ad1a3d10804b6f0dffbd5/BWAPI4J/src/test/java/org/openbw/bwapi4j/unit/BuildingTest.java) to help with refactoring. Any is welcome to refactor these methods.

**Comment by muandrew** [comment]
@adakitesystems I can take this one.

Just curious, do you know why the calculation for distance between TilePosition, Position is using Double math while Unit is using approximation? I can leave the behavior the same but it doesn't look intentional for the math to be different.

**Comment by adakitesystems** [comment]
Thanks, @muandrew!
> Just curious, do you know why [...]

I have no idea. Pinging @IMP-42 for clarification.

**Comment by adakitesystems** [comment]
@muandrew, ByteKeeper and I found a couple bugs with the angle calculations. So, if you find math to be wrong somewhere and you can explain the problem and/or fix it, please do so. Thanks again.

**Comment by muandrew** [comment]
It isn't a problem with the math per-say but the consistency of what's being calculated.
Like mentioned above, some distances are calculated with the normal euclidian distance math d = sqrt(x^2 + y^2) but some distances are approximate distances which makes the calculation faster but not as accurate. Alternatively I can create methods for both types, like getDistance and getApproximateDistance. Bot creators can then chose what they want.

**Comment by JasperGeurtz** [comment]
Approximate distance is what Broodwar uses internally. This should be preferred in most cases

**Comment by adakitesystems** [comment]
This issue has been resolved thanks to @muandrew.
