### ISSUE TITLE
How to configure logging?

### ISSUE THREAD

**Issue by nturley** [OpenBW/BWAPI4J#5]
So I was trying to use this with jython (which works great), and I'm getting totally spammed from console logging. I'm not too familiar with apache log4j. Can I configure it programmatically? Do I need to put a config file at a particular path?

**Comment by dgant** [comment]
Jython? Neat :)

I believe log4j supports both approaches.

**Comment by nturley** [comment]
I figured this out. My bwapi4j jar file had a config file that puts the BW class at trace level, so even if I configured the root logger to a different level I was still getting spammed by the BW class. Modifying the bwapi4j config file solved the problem.
