### ISSUE TITLE
VsDevCmd for VS2017

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#51]
If a user's local installation of VS2017 is not the Community version (i.e. Enterprise or Professional), the provided `VsDevCmd.bat` will fail due to an incorrect path to the system's `VsDevCmd.bat`. 

An attempt to resolve the path programmatically was made in commit https://github.com/OpenBW/BWAPI4J/commit/af02f9f27614413340083bee0ded95d6ba147462 but [failed on AppVeyor](https://ci.appveyor.com/project/adakitesystems/bwapi4j/build/0.8.39) with the error: `Failed to find file: VsDevCmd.bat`. The commit was reverted.

I'm open to pull requests or solutions to fix this.

**Comment by Jabbo16** [comment]
Testing a bit I discovered the reason why its failing to find it.

The proper Appveyor location its `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat`, but (getProgramFilesDirectory())[https://github.com/OpenBW/BWAPI4J/blob/af02f9f27614413340083bee0ded95d6ba147462/BWAPI4J/build.gradle#L240] its returning the non x86 path instead.

I managed to fix it by detecting in that method if the gradle script its being ran from within appveyor by setting up a custom env variable (could also be done using already created appveyor's envs).

I added this inside `appveyor.yml`:

```yaml
install:
  - cmd: set appveyor=yes
```

And modified the method `getProgramFilesDirectory()` inside `build.gradle`:

```java
static String getProgramFilesDirectory() {
        final String programFilesDirectory = SYSTEM_ENVIRONMENT_VARIABLES.get(PROGRAM_FILES_KEY);
        if(SYSTEM_ENVIRONMENT_VARIABLES.get("APPVEYOR").equals("yes")) return programFilesDirectory + " (x86)";;
        if (doesDirectoryExist(programFilesDirectory)) {
            return programFilesDirectory;
        } else if (doesDirectoryExist(programFilesDirectory + " (x86)")) {
            return programFilesDirectory + " (x86)";
        } else {
            throw new IllegalStateException("Failed to determine Program Files directory from environment variable: " + PROGRAM_FILES_KEY);
        }
    }
```

**Comment by adakitesystems** [comment]
Excellent debugging skills! I will try this out later. Thanks!

> Another thing I thought its just returning always the x86 ProgramFiles path, I think that Visual Studio always gets installed by default to that folder

I have a Win7 32-bit install and every VS version was installed to `C:\Program Files` except for the `C:\Program Files (x86)\Microsoft Visual Studio 14.0` runtime package. 

The mentioned commit af02f9f worked on my system where my path is `C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat`.

**Comment by Jabbo16** [comment]
Oh right my bad, too used to 64bits OSs.

Then maybe another fix could be checking first the non x86 path and if not found test then the x86 one.

**Comment by adakitesystems** [comment]
That fix worked. Very nice! Thanks again!
