### ISSUE TITLE
Add option to disable OpenBW UI from the bot

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#55]
After OpenBW has been compiled with UI, I think it is possible for the module to disable the UI by calling a (static or global ?) function such as `enableUI(false);` or something similar. If it is possible, BWAPI4J should provide some way to call that code.

*Note: I am not referring to disabling the UI by passing a runtime argument to* `BWAPILauncher`*.*

**Comment by dgant** [comment]
"The UI can be disabled either by setting environment variable OPENBW_ENABLE_UI=0 or calling Broodwar->setGUI(false)."

**Comment by adakitesystems** [comment]
Thanks, @dgant!
