### ISSUE TITLE
Can't irradiate mechanical units

### ISSUE THREAD

**Issue by Jabbo16** [OpenBW/BWAPI4J#57]
Ingame you can use the `Science Vessel` ability `Irradiate` on mechanical units like a `Siege Tank`, but the method provided by bwapi4j to irradiate needs `Organic` as a parameter: 

`ScienceVessel.irradiate(Organic unit)`.

Using `Organic` its also wrong because you cant irradiate some units that implement this class, for example some zerg buildings.

Also a `Science Vessel` cannot irradiate itself but can irradiate another vessel, maybe this could also be checked before trying to cast the ability.

[Reference](https://liquipedia.net/starcraft/Irradiate)

**Comment by adakitesystems** [comment]
Thanks for the bug report, @Jabbo16!

> Also a Science Vessel cannot irradiate itself but can irradiate another vessel, maybe this could also be checked before trying to cast the ability.

I disagree with this check. Unless we want to do similar checks everywhere else like `selfUnit.attack(selfUnit)` or `selfVessel.defenseMatrix(selfVessel)` etc.
