### ISSUE TITLE
WorkerUnit class (inc. build command for all)

### ISSUE THREAD

**Issue by Venorcis** [OpenBW/BWAPI4J#6]
This abstract class would be useful for SCVs/Drones/Probes.
There is now inconsistency in all of them in e.g. the build command. SCVs use a TilePosition, Probes use a Position, and Drones don't have the command at all (whilst this is supported in BWAPI).

**Comment by adakitesystems** [comment]
Good idea and thanks for the suggestion! @Bytekeeper's proposed solution in commit https://github.com/Bytekeeper/BWAPI4J/commit/3807f8e18e09f5d557be486c0cb04517f376dbd3 will most likely be used. 

This issue can be considered closed but will remain open until merged into the main branch.

**Comment by adakitesystems** [comment]
Merged.
