### ISSUE TITLE
Missing Game#setScreenPosition

### ISSUE THREAD

**Issue by JasperGeurtz** [OpenBW/BWAPI4J#67]
Useful for debugging 

```Java
public void setScreenPosition(int x, int y) {
    setScreenPosition_native(pointer, x, y);
}

public void setScreenPosition(Position p) {
    setScreenPosition_native(pointer, p);
}
```
https://github.com/vjurenka/BWMirror/blob/8f8882f7b0166ba73a5e33a48e241231926fa758/api/bwapi/Game.java#L116

**Comment by adakitesystems** [comment]
This commit doesn't fully fix it. The modified bridge code was not included in this commit. The next commit does.
