### ISSUE TITLE
Do not manually manage the frame count

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#68]
I highly suspect this is wrong:
https://github.com/OpenBW/BWAPI4J/blob/8d4e6d6846b4aa8e64db57901de92971d719032a/BWAPI4J/src/main/java/org/openbw/bwapi4j/BW.java#L747
https://github.com/OpenBW/BWAPI4J/blob/8d4e6d6846b4aa8e64db57901de92971d719032a/BWAPI4J/src/main/java/org/openbw/bwapi4j/BW.java#L705

We cannot manually handle the frame count because the frame count stays the same during a pause and when the game is preparing to exit to the score screen. We are already reading the true frame count from BWAPI and supplying it to the user via `InteractionHandler#getFrameCount()`. This value should be used.

I will fix it later. This issue is so I do not forgot or if someone has relevant information to this.

**Comment by JasperGeurtz** [comment]
For the similar reasons I think 
```Java
lastCommandFrame = getCurrentFrame();
lastCommand = unitCommandType;
```
shouldn't be updated in UnitImpl.issueCommand
because this might create unexpected behaviour (especially with LatCom disabled)

https://github.com/OpenBW/BWAPI4J/blob/d25006361d97c09052961c81e933e48401f48ee6/BWAPI4J/src/main/java/org/openbw/bwapi4j/unit/UnitImpl.java#L517

**Comment by adakitesystems** [comment]
> shouldn't be updated in UnitImpl.issueCommand

I think this is a different issue? Or is everything "fixed" now?

**Comment by JasperGeurtz** [comment]
Different issue yeah

**Comment by adakitesystems** [comment]
Ah yes I see now. Thanks for mentioning this.
