### ISSUE TITLE
Probable inaccuracy with "getLastCommand" and "getLastCommandFrame"

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#69]
As per ~~@Jabbo16~~ @JasperGeurtz's reply in https://github.com/OpenBW/BWAPI4J/issues/68, there is a probable inaccuracy with `Unit#getLastCommand` and `Unit#getLastCommandFrame`. I suggest we update the `lastCommandXXXX` fields from the C++ BWAPI side into Java every time an issue command is invoked.

Does anyone have any concerns about this?

Edit: Sorry for the mix up in names, @JasperGeurtz!

**Comment by Jabbo16** [comment]
It was actually @JasperGeurtz the one that discovered the inaccuracy

**Comment by JasperGeurtz** [comment]
In fact they already are

```Java
unit.lastCommand = UnitCommandType.values()[unitData[index + LAST_COMMAND_TYPE_ID_INDEX]];
unit.lastCommandFrame = unitData[index + LAST_COMMAND_FRAME_INDEX];
```

So they shouldn't be updated during the frame IMHO

**Comment by adakitesystems** [comment]
I agree, @JasperGeurtz. That value will be updated depending on if a command is successful as seen here: https://github.com/bwapi/bwapi/blob/59b14af21b3c881ce06af8b1ea1d63fa3c8b2df0/bwapi/BWAPIClient/Source/UnitImpl.cpp#L20-L64

**Comment by adakitesystems** [comment]
Even better might be to return a small int array of values every time a command is issued instead of the current `boolean` return value. The int array would contain the following:
1. `0=false` or `1=true` depending if the command was sent successfully
2. type ID of the last command type (or the entire command with full details)
3. last command frame

**Comment by JasperGeurtz** [comment]
I'm not a fan, returning an array is not OOP/code smell, and it makes the method needlessly complex.
Forcing the caller to parse the array for success etc.
A method should do one thing.

I'm more in favor of keeping it like it is. If a user wants to know the last commandtype/commandframe, they can query it via getLastCommandType etc.

**Comment by adakitesystems** [comment]
I think you misunderstood me or I didn't explain properly. The user would not receive an int array. The bridge will send the int array with the details and then set `lastCommand` and `lastCommandFrame` appropriately. I will submit a PR soon and you will see what I mean.

**Comment by JasperGeurtz** [comment]
I misunderstood

But they are already set on per frame basis in the BirdgeUtils. They wont change during the frame afaik so returning them via the bridge might not be useful

**Comment by adakitesystems** [comment]
You are correct they are set on a per frame basis in BWAPI4J currently. However, that is a bug. 

I tested using both a C++ module and C++ client which prove `lastCommand` and `lastCommandFrame` can change mid-frame after a command is issued using the following code in the `onFrame` callback:
```cpp
	  for (const auto &u : BWAPI::Broodwar->self()->getUnits()) {
		  if (u->getType().isWorker()) {
			  {
				  std::ostringstream oss;
				  oss << "f=" << BWAPI::Broodwar->getFrameCount() << ", uid=" << u->getID() << ", lcid=" << u->getLastCommand().getType().getID() << ", lcf=" << u->getLastCommandFrame();
				  BWAPI::Broodwar->sendText("%s", oss.str().c_str());
			  }
			  {
				  u->move(BWAPI::Position(0, 0));
				  std::ostringstream oss;
				  oss << "f=" << BWAPI::Broodwar->getFrameCount() << ", uid=" << u->getID() << ", lcid=" << u->getLastCommand().getType().getID() << ", lcf=" << u->getLastCommandFrame();
				  BWAPI::Broodwar->sendText("%s", oss.str().c_str());
			  }
			  {
				  u->attack(BWAPI::Position(0, 0));
				  std::ostringstream oss;
				  oss << "f=" << BWAPI::Broodwar->getFrameCount() << ", uid=" << u->getID() << ", lcid=" << u->getLastCommand().getType().getID() << ", lcf=" << u->getLastCommandFrame();
				  BWAPI::Broodwar->sendText("%s", oss.str().c_str());
				  BWAPI::Broodwar->sendText("", oss.str().c_str());
			  }
			  break;
		  }
	  }
```
Here is the output: ![lcf](https://user-images.githubusercontent.com/22711643/44576110-faaf2180-a74a-11e8-81df-e6115c08f346.png)

**Comment by adakitesystems** [comment]
Sorry for the confusion. `lastCommand` and `lastCommandFrame` are updated in BWAPI4J per frame **AND** after each successful command. There is no bug with `lastCommand` and `lastCommandFrame` of which I am currently aware. The current code is correct and will be left as is. Thanks for the help, @JasperGeurtz!
