### ISSUE TITLE
Exception when calling getTransport on a Unit inside a Bunker

### ISSUE THREAD

**Issue by Jabbo16** [OpenBW/BWAPI4J#76]
Latest `develop` has a bug when calling `getTransport` of an `Unit` thats inside a `Bunker`

The bug is in `MobileUnitImpl.java`

```java
public MobileUnit getTransport() {
    return (MobileUnit) transport;
}
```

`Bunker`s are no `MobileUnit` so this method throws:

`java.lang.ClassCastException: org.openbw.bwapi4j.unit.Bunker cannot be cast to org.openbw.bwapi4j.unit.MobileUnit`

This impl also differs from the Interface `MobileUnit.java` where `getTransport` correctly returns `Unit`:

**Comment by Bytekeeper** [comment]
I think it should be `Loadable` in both cases.

**Comment by Bytekeeper** [comment]
@Jabbo16 Could you retry?

**Comment by Jabbo16** [comment]
it works with `Loadable`, thanks! ❤️
