### ISSUE TITLE
Missing draw commands

### ISSUE THREAD

**Issue by adakitesystems** [OpenBW/BWAPI4J#77]
Thanks to @JasperGeurtz for mentioning this on BWAPI4J Discord:
> bwapi4j is missing the drawTriangle and drawEllipse I think
(and maybe draw dot)

I assume the draw commands were manually added as needed when BWAPI4J first started. However, manually adding shape methods and their variations is annoying and prone to error. If possible, I recommend using the recently added parser to generate all of the draw commands in Java and C++ by creating classes or enums that hold shapes and coordinate types (draw shape to screen vs draw shape to map).

- [x] ~~Determine list of all shapes. e.g. Dot, Line, Box, Circle, Ellipse, Triangle, Text~~ Shapes: None(0), Text(1), Box(2), Triangle(3), Circle(4), Ellipse(5), Dot(6), Line(7);
- [x] ~~Determine list of all coord types. e.g. Map, Screen, Mouse~~ Coord types: None(0), Screen(1), Map(2), Mouse(3);

**Comment by JasperGeurtz** [comment]
The `Mouse` variants also seem to be missing

**Comment by JasperGeurtz** [comment]
Shapes
https://github.com/JasperGeurtz/JBWAPI/blob/master/src/main/java/bwapi/Shape.java

Coordinates
https://github.com/JasperGeurtz/JBWAPI/blob/master/src/main/java/bwapi/Coordinate.java

**Comment by adakitesystems** [comment]
Thanks for the list of shapes and coord types @JasperGeurtz!
